using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Stock
{
	#region Fields
	private string name;
	private float pricePerShare;
	private int sharesOwned;
	private float incomePerShare;
	private float totalIncome;
	#endregion

	#region Properties
	public string Name { get { return name; } }
	public float PricePerShare { get { return pricePerShare; } }
	public int SharesOwned { get { return sharesOwned; } }
	public float IncomePerShare { get { return incomePerShare; } }
	public float TotalIncome { get { return totalIncome; } }
	#endregion

	#region Constructor
	/// <summary>
	/// Create a new Stock
	/// </summary>
	/// <param name="name">The name of the stock</param>
	/// <param name="pricePerShare">The initial amount each share of this stock counts</param>
	/// <param name="sharesOwned">The starting number of shares the player owns</param>
	/// <param name="incomePerShare">The amount of income each share of this stock generates passively</param>
	public Stock(string name, float pricePerShare, int sharesOwned, float incomePerShare)
	{
		this.name = name;
		this.pricePerShare = pricePerShare;
		this.sharesOwned = sharesOwned;
		this.incomePerShare = incomePerShare;
		totalIncome = sharesOwned * incomePerShare;
	}
	#endregion
	
	#region Methods
	/// <summary>
	/// Buys shares of the current stock
	/// </summary>
	/// <param name="sharesBought">The number of shares bought</param>
	public void BuyStock(int sharesBought)
	{
		// Check if the player has enough money to buy shares
		if(/*PLAYER_MONEY*/ 0.0f < pricePerShare * sharesBought)
			return;

		sharesOwned += sharesBought;

		// Recalculates the total income generated by all of the shares of the stock
		totalIncome = sharesOwned * incomePerShare;
	}
	/// <summary>
	/// Overloaded method to buy 1 share
	/// </summary>
	public void BuyStock()
	{
		BuyStock(1);
	}
	#endregion
}
